# --- RAM optimization ---
org.gradle.jvmargs=-Xmx4G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -Dfile.encoding=UTF-8

# --- CPU optimization ---
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.daemon=true

# --- Caches and performances ---
org.gradle.caching=true
org.gradle.configuration-cache=true
android.nonTransitiveRClass=true

# --- Android & Kotlin configuration ---
android.useAndroidX=true
kotlin.code.style=official
android.uniquePackageNames=true

# --- Dependencies management and Proguard ---
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false

# --- Removing AGP warnings ---
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
